# This is for deployment of service using helm which manages the pods
# All variables defined in values.yaml

apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.name }}
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: {{ .Values.port }}
  selector:
    app: {{ .Values.name }}
